# Generated by Django 5.1.6 on 2025-03-12 14:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, default='New', max_length=100)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('warranty', models.CharField(blank=True, default='No Warranty', max_length=50)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('generation', models.CharField(blank=True, max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('origin_country', models.CharField(blank=True, max_length=100)),
                ('power_consumption', models.CharField(blank=True, max_length=50)),
                ('battery_life', models.CharField(blank=True, max_length=50)),
                ('charging_time', models.CharField(blank=True, max_length=50)),
                ('connectivity', models.CharField(blank=True, max_length=100)),
                ('processor', models.CharField(blank=True, max_length=100)),
                ('storage_capacity', models.CharField(blank=True, max_length=100)),
                ('screen_size', models.CharField(blank=True, max_length=50)),
                ('resolution', models.CharField(blank=True, max_length=100)),
                ('weight_capacity', models.CharField(blank=True, max_length=50)),
                ('assembly_required', models.BooleanField(blank=True, null=True)),
                ('style', models.CharField(blank=True, max_length=100)),
                ('water_resistant', models.BooleanField(blank=True, null=True)),
                ('upholstery_material', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('fabric_type', models.CharField(blank=True, max_length=100)),
                ('washing_instructions', models.TextField(blank=True)),
                ('shoe_type', models.CharField(blank=True, max_length=100)),
                ('closure_type', models.CharField(blank=True, max_length=100)),
                ('fuel_type', models.CharField(blank=True, max_length=50)),
                ('transmission', models.CharField(blank=True, max_length=50)),
                ('mileage', models.CharField(blank=True, max_length=50)),
                ('engine_capacity', models.CharField(blank=True, max_length=50)),
                ('top_speed', models.CharField(blank=True, max_length=50)),
                ('number_of_seats', models.IntegerField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True)),
                ('calories', models.CharField(blank=True, max_length=50)),
                ('dietary_info', models.CharField(blank=True, max_length=100)),
                ('package_size', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('paper_type', models.CharField(blank=True, max_length=100)),
                ('recommended_age', models.CharField(blank=True, max_length=50)),
                ('safety_certifications', models.CharField(blank=True, max_length=100)),
                ('battery_required', models.BooleanField(blank=True, null=True)),
                ('interactive_features', models.CharField(blank=True, max_length=100)),
                ('skin_type', models.CharField(blank=True, max_length=100)),
                ('scent', models.CharField(blank=True, max_length=100)),
                ('application_method', models.CharField(blank=True, max_length=100)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('sport_type', models.CharField(blank=True, max_length=100)),
                ('weather_resistant', models.BooleanField(blank=True, null=True)),
                ('material_durability', models.CharField(blank=True, max_length=100)),
                ('gemstone', models.CharField(blank=True, max_length=100)),
                ('metal_type', models.CharField(blank=True, max_length=100)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('certification', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('STAFF', 'Staff'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Home Appliances', 'Home Appliances'), ('Furniture', 'Furniture'), ('Accessories', 'Accessories'), ('Automotives', 'Automotives'), ('Toys&Games', 'Toys&Games')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('image1', models.ImageField(blank=True, default='', null=True, upload_to='products/')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='products/')),
                ('image3', models.ImageField(blank=True, default='', null=True, upload_to='products/')),
                ('image4', models.ImageField(blank=True, default='', null=True, upload_to='products/')),
                ('stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(choices=[('Arusha', 'Arusha'), ('Dar es Salaam', 'Dar es Salaam'), ('Dodoma', 'Dodoma'), ('Geita', 'Geita'), ('Iringa', 'Iringa'), ('Kagera', 'Kagera'), ('Katavi', 'Katavi'), ('Kigoma', 'Kigoma'), ('Kilimanjaro', 'Kilimanjaro'), ('Lindi', 'Lindi'), ('Manyara', 'Manyara'), ('Mara', 'Mara'), ('Mbeya', 'Mbeya'), ('Morogoro', 'Morogoro'), ('Mtwara', 'Mtwara'), ('Mwanza', 'Mwanza'), ('Njombe', 'Njombe'), ('Pemba North', 'Pemba North'), ('Pemba South', 'Pemba South'), ('Rukwa', 'Rukwa'), ('Ruvuma', 'Ruvuma'), ('Shinyanga', 'Shinyanga'), ('Singida', 'Singida'), ('Simiyu', 'Simiyu'), ('Songwe', 'Songwe'), ('Tabora', 'Tabora'), ('Tanga', 'Tanga')], default='Dar es Salaam', max_length=50)),
                ('tech', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.tech')),
            ],
        ),
    ]
