# Generated by Django 5.1.6 on 2025-03-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Home Appliances', 'Home Appliances'), ('Furniture', 'Furniture'), ('Accessories', 'Accessories'), ('Automotives', 'Automotives'), ('Toys&Games', 'Toys&Games')], max_length=50),
        ),
    ]
