# Generated by Django 5.1.6 on 2025-03-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_product_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
