# Generated by Django 5.1.7 on 2025-07-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_receipt_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Enter the message to be displayed to users')),
                ('title', models.CharField(blank=True, help_text='Optional title for the message', max_length=255, null=True)),
                ('start_date', models.DateTimeField(help_text='When this message should start showing')),
                ('end_date', models.DateTimeField(help_text='When this message should stop showing')),
                ('is_active', models.BooleanField(default=True, help_text='Manually disable the message if needed')),
                ('position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', help_text='Which side of the screen to show the message on', max_length=10)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority messages show on top if multiple are active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-start_date'],
            },
        ),
    ]
