# Generated by Django 5.1.5 on 2025-02-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_productimage_alt_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('Arusha', 'Arusha'), ('Dar es Salaam', 'Dar es Salaam'), ('Dodoma', 'Dodoma'), ('Geita', 'Geita'), ('Iringa', 'Iringa'), ('Kagera', 'Kagera'), ('Katavi', 'Katavi'), ('Kigoma', 'Kigoma'), ('Kilimanjaro', 'Kilimanjaro'), ('Lindi', 'Lindi'), ('Manyara', 'Manyara'), ('Mara', 'Mara'), ('Mbeya', 'Mbeya'), ('Morogoro', 'Morogoro'), ('Mtwara', 'Mtwara'), ('Mwanza', 'Mwanza'), ('Njombe', 'Njombe'), ('Pemba North', 'Pemba North'), ('Pemba South', 'Pemba South'), ('Rukwa', 'Rukwa'), ('Ruvuma', 'Ruvuma'), ('Shinyanga', 'Shinyanga'), ('Singida', 'Singida'), ('Simiyu', 'Simiyu'), ('Songwe', 'Songwe'), ('Tabora', 'Tabora'), ('Tanga', 'Tanga')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
