# Generated by Django 5.1.7 on 2025-08-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_adminmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='seller_approval',
            field=models.BooleanField(blank=True, help_text="Seller's decision on payment approval", null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='seller_notes',
            field=models.TextField(blank=True, help_text="Seller's notes on the payment"),
        ),
        migrations.AddField(
            model_name='payment',
            name='seller_reviewed',
            field=models.BooleanField(default=False, help_text='Whether the seller has reviewed this payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='seller_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
