# Generated by Django 5.1.7 on 2025-08-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product_dislikes_count_product_likes_count_and_more'),
        ('myapp', 'add_password_reset_code'),
    ]

    operations = [
    ]
