# Generated by Django 5.1.5 on 2025-02-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product_location_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='technical_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
