# Generated by Django 5.1.7 on 2025-08-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_merge_20250810_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike')], max_length=10),
        ),
    ]
