# Generated by Django 5.1.7 on 2025-08-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_productinteraction_interaction_type'),
        ('myapp', 'add_whatsapp_recovery_preference'),
    ]

    operations = [
    ]
