# Generated by Django 5.1.5 on 2025-02-12 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_product_image4_product_image5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image5',
        ),
    ]
