# Generated by Django 5.1.7 on 2025-08-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_passwordresetcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name for payments', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True, help_text='Shop description and details'),
        ),
        migrations.AddField(
            model_name='seller',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications'),
        ),
        migrations.AddField(
            model_name='seller',
            name='location',
            field=models.CharField(blank=True, choices=[('Arusha', 'Arusha'), ('Dar es Salaam', 'Dar es Salaam'), ('Dodoma', 'Dodoma'), ('Geita', 'Geita'), ('Iringa', 'Iringa'), ('Kagera', 'Kagera'), ('Katavi', 'Katavi'), ('Kigoma', 'Kigoma'), ('Kilimanjaro', 'Kilimanjaro'), ('Lindi', 'Lindi'), ('Manyara', 'Manyara'), ('Mara', 'Mara'), ('Mbeya', 'Mbeya'), ('Morogoro', 'Morogoro'), ('Mtwara', 'Mtwara'), ('Mwanza', 'Mwanza'), ('Njombe', 'Njombe'), ('Pemba North', 'Pemba North'), ('Pemba South', 'Pemba South'), ('Rukwa', 'Rukwa'), ('Ruvuma', 'Ruvuma'), ('Shinyanga', 'Shinyanga'), ('Singida', 'Singida'), ('Simiyu', 'Simiyu'), ('Songwe', 'Songwe'), ('Tabora', 'Tabora'), ('Tanga', 'Tanga')], help_text='Shop location', max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='mobile_money',
            field=models.CharField(blank=True, help_text='Mobile money number for payments', max_length=15),
        ),
        migrations.AddField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Primary contact phone number', max_length=15),
        ),
        migrations.AddField(
            model_name='seller',
            name='sms_notifications',
            field=models.BooleanField(default=False, help_text='Receive SMS notifications'),
        ),
        migrations.AddField(
            model_name='seller',
            name='whatsapp_notifications',
            field=models.BooleanField(default=True, help_text='Receive WhatsApp notifications'),
        ),
        migrations.AddField(
            model_name='seller',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp business number', max_length=15),
        ),
    ]
