# Generated by Django 5.1.5 on 2025-02-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_product_image5'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='application_method',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='assembly_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='battery_life',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='battery_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Generic', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='certification',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='charging_time',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='closure_type',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='connectivity',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='dietary_info',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='edition',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_capacity',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_type',
            field=models.CharField(default='Cotton', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_type',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='gemstone',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(default='Unisex', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='product',
            name='interactive_features',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='material_durability',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='metal_type',
            field=models.CharField(default='Gold', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='mileage',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_pieces',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_seats',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='product',
            name='origin_country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='package_size',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='pages',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='paper_type',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='power_consumption',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='recommended_age',
            field=models.CharField(default='All Ages', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='resolution',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_certifications',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='scent',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_size',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_type',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.CharField(default='All Skin Types', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sport_type',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_capacity',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(default='Modern', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='top_speed',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='transmission',
            field=models.CharField(default='Manual', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='upholstery_material',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='washing_instructions',
            field=models.TextField(default='Machine wash cold'),
        ),
        migrations.AddField(
            model_name='product',
            name='water_resistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='weather_resistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_capacity',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
