# Generated by Django 5.1.7 on 2025-09-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_seller_account_number_seller_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='lipa_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
