# Generated by Django 5.1.5 on 2025-02-15 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_product_application_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='application_method',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='assembly_required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='battery_life',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='battery_required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='Generic', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='certification',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='charging_time',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='closure_type',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='connectivity',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='dietary_info',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='edition',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_capacity',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_type',
            field=models.CharField(blank=True, default='Cotton', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_type',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='gemstone',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, default='Unisex', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AddField(
            model_name='product',
            name='interactive_features',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='material_durability',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='metal_type',
            field=models.CharField(blank=True, default='Gold', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='mileage',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_pieces',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_seats',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='origin_country',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='package_size',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='pages',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='paper_type',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='power_consumption',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='recommended_age',
            field=models.CharField(blank=True, default='All Ages', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='resolution',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_certifications',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='scent',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_size',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_type',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.CharField(blank=True, default='All Skin Types', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sport_type',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_capacity',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, default='Modern', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='top_speed',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='transmission',
            field=models.CharField(blank=True, default='Manual', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='upholstery_material',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='washing_instructions',
            field=models.TextField(blank=True, default='Machine wash cold'),
        ),
        migrations.AddField(
            model_name='product',
            name='water_resistant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weather_resistant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_capacity',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, default='New', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='generation',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_year',
            field=models.IntegerField(blank=True, default=2024, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, default='No Warranty', max_length=50),
        ),
    ]
