# Generated by Django 5.1.5 on 2025-02-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_product_application_method_product_assembly_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('Dar es Salaam', 'Dar es Salaam')], default='Dar es Salaam', max_length=50),
        ),
    ]
