# Generated by Django 5.1.7 on 2025-03-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_product_assembly_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='product_types',
        ),
    ]
