# Generated by Django 5.1.7 on 2025-04-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_seller_product_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
