# Generated by Django 5.1.7 on 2025-04-13 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.CharField(max_length=255)),
                ('secondary', models.CharField(max_length=255)),
                ('high_school', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('talents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ParentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('residence', models.CharField(max_length=255)),
                ('is_mother', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('signature', models.ImageField(upload_to='signatures/')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField()),
                ('features', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='SellerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('BRONZE', 'Bronze Booster'), ('SILVER', 'Silver Spotlight'), ('GOLD', 'Gold Galaxy')], max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.seller')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('third_name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20)),
                ('spouse_details', models.TextField(blank=True, null=True)),
                ('nationality', models.CharField(max_length=100)),
                ('passport_nida', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('drivers_license', models.CharField(max_length=50)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('chairperson_name', models.CharField(max_length=255)),
                ('chairperson_post', models.CharField(max_length=255)),
                ('chairperson_signature', models.ImageField(upload_to='signatures/')),
                ('chairperson_stamp', models.ImageField(upload_to='stamps/')),
                ('nida_passport_doc', models.FileField(upload_to='documents/')),
                ('driving_license_doc', models.FileField(upload_to='documents/')),
                ('police_clearance_doc', models.FileField(upload_to='documents/')),
                ('educational_certificates_doc', models.FileField(upload_to='documents/')),
                ('contract_rules', models.TextField()),
                ('worker_signature', models.ImageField(upload_to='signatures/')),
                ('lawyer_name', models.CharField(max_length=255)),
                ('lawyer_signature', models.ImageField(upload_to='signatures/')),
                ('lawyer_stamp', models.ImageField(upload_to='stamps/')),
                ('ceo_name', models.CharField(max_length=255)),
                ('ceo_signature', models.ImageField(upload_to='signatures/')),
                ('ceo_stamp', models.ImageField(upload_to='stamps/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('education_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.educationrecord')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='father_contracts', to='myapp.parentdetails')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_contracts', to='myapp.parentdetails')),
                ('referee1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee1_contracts', to='myapp.referee')),
                ('referee2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee2_contracts', to='myapp.referee')),
            ],
        ),
    ]
