# Generated by Django 5.1.7 on 2025-04-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_product_attributes_product_video_productattribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='assembly_required',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='battery_required',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_pieces',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_seats',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pages',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='water_resistant',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
