# Generated by Django 5.1.7 on 2025-04-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_product_assembly_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='product_videos/'),
        ),
        migrations.AlterField(
            model_name='workercontract',
            name='ceo_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='workercontract',
            name='ceo_stamp',
            field=models.ImageField(blank=True, null=True, upload_to='stamps/'),
        ),
        migrations.AlterField(
            model_name='workercontract',
            name='chairperson_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='workercontract',
            name='chairperson_stamp',
            field=models.ImageField(blank=True, null=True, upload_to='stamps/'),
        ),
        migrations.AlterField(
            model_name='workercontract',
            name='lawyer_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='workercontract',
            name='lawyer_stamp',
            field=models.ImageField(blank=True, null=True, upload_to='stamps/'),
        ),
        migrations.AlterField(
            model_name='workercontract',
            name='worker_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
